### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by viveksubbarao** [drinkbeer/DFS-Python#1]
Functions on the server side throw exceptions that can potentially halt the server. Need to catch these and ensure that the application is running. Need to look at all server side functionality and what exception s they thow to handle the same.

**Comment by drinkbeer** [comment]
OK. Can you show me more details about the bugs? like error no, or error msg

**Comment by viveksubbarao** [comment]
Each of the "os" functions on the server side can fail. Failure here does not mean they return -1 or +1, they throw an exception. We need to handle them. An example is the `os.lstat` function used in dfs_getattr function on the server side. This function throws OSError exception if the file does not exist.

**Comment by viveksubbarao** [comment]
Why was this issue closed ? I do not see any code checkin that went into fixing this.
