### ISSUE TITLE
Journaling needs to be implemented

### ISSUE THREAD

**Issue by viveksubbarao** [drinkbeer/DFS-Python#4]
The journaling functionality in the master needs to be throughly tested. It should provide a easy to use interface to figure out the latest version of a file and which holds it. @drinkbeer

**Comment by drinkbeer** [comment]
I synchronize servers based on file timestamp, not Journaling. I am wondering the necessarily of Journaling. Where can we use Journaling, as I have already implemented it?

**Comment by viveksubbarao** [comment]
Journaling is not needed as of now. Consistency is implemented using timestamps. Journaling might be required in the future. Hence changing the status of the bug to won't fix.
