### ISSUE TITLE
Consistency protocol needs to be implemented

### ISSUE THREAD

**Issue by viveksubbarao** [drinkbeer/DFS-Python#5]
A way to implement consistency among different copies of the same file is required. #4

**Comment by drinkbeer** [comment]
I updated consistency.
Master will launch a thread, which will check and synchronize the files in two folder 'S1', 'S2' in every second. The check is based on the timestamp of the files, not by timestamp in Journaling.
So if we synchronize not based on Journaling, what's the meaning of Journaling?

**Comment by viveksubbarao** [comment]
Fixed by commit 39f1410
